name: Android UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ui_tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Clone the repository
    - name: Check out repository
      uses: actions/checkout@v2

    # 2. Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    # 3. Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3
        cache: gradle

    # 4. Start Android emulator for UI tests
    - name: Start Android emulator
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: Nexus 6
        emulator-options: "-no-window -no-audio"
        disable-animations: true

    # 5. Wait for the Android Emulator to boot
    - name: Wait for Android Emulator to boot
      run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

    # 6. Run UI tests
    - name: Run UI tests
      run: ./gradlew connectedAndroidTest

    # 7. Upload UI test results (optional)
    - name: Upload UI test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: ui-test-results
        path: app/build/reports/androidTests/connected
